---
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: aws-smtp-relay
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
      - "6"
    ldflags:
      - -s -w

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: "goreleaser.Dockerfile"
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/moulick/{{ .ProjectName }}:latest-amd64
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.url="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.authors="moulickaggarwal"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: "goreleaser.Dockerfile"
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-arm64v8
      - ghcr.io/moulick/{{ .ProjectName }}:latest-arm64v8
    build_flag_templates:
      - --pull
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.url="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.authors="moulickaggarwal"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"
  - use: buildx
    goos: linux
    goarch: arm
    goarm: "7"
    dockerfile: "goreleaser.Dockerfile"
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-armv7
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-armv7
      - ghcr.io/moulick/{{ .ProjectName }}:latest-armv7
    build_flag_templates:
      - --pull
      - --platform=linux/arm/v7
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.source="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.url="https://github.com/Moulick/aws-smtp-relay"
      - --label=org.opencontainers.image.authors="moulickaggarwal"
      - --label=org.opencontainers.image.created="{{ .Date }}"
      - --label=org.opencontainers.image.title="{{ .ProjectName }}"
      - --label=org.opencontainers.image.revision="{{ .FullCommit }}"
      - --label=org.opencontainers.image.version="{{ .Version }}"
#
docker_manifests:
  # Github Container Registry
  - name_template: ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-amd64
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-arm64v8
      - ghcr.io/moulick/{{ .ProjectName }}:{{ .Tag }}-armv7
  - name_template: ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-arm64v8
      - ghcr.io/moulick/{{ .ProjectName }}:v{{ .Major }}-armv7
  - name_template: ghcr.io/moulick/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/moulick/{{ .ProjectName }}:latest-amd64
      - ghcr.io/moulick/{{ .ProjectName }}:latest-arm64v8
      - ghcr.io/moulick/{{ .ProjectName }}:latest-armv7

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Tag}}-devel"

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: mod
  gobinary: go

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
